### ISSUE TITLE
Segmentation Fault in line 78 of /src/OMSimRunManager.cc

### ISSUE THREAD

**Issue by asam53** [waleey/bulkice_doumeki#6]
Code crashes upon deleting fRunManager in line 78 of OMSimRunManager.cc

`::::::::::::::this is the end of a run:::::::::::::
Deleting vismanager
Graphics systems deleted.
Visualization Manager deleting...
Deleting runmanager
Segmentation fault: 11`

**Comment by waleey** [comment]
HI! I am unable to reproduce the same issue. Could you provide me a little more details? Like, does it crash exactly when we call `delete fRunManager` ? I see a segmentation fault at the end when I close OpenGL and close the program. Also, were you able to use OpenGL with other example Geant4 programs? I was just trying to make sure your OpenGL installation is correct.

**Comment by asam53** [comment]
Hi Waly, 

We added the following strings for each delete command to see where the code breaks in /src/OMSimRunManager.cc. Let me know if this helps. Also, OpenGL worked when I ran the geant4 example B1. 

`{
    std::cout << "::::::::::::::this is the end of a run:::::::::::::"<< std::endl;

    #ifdef G4VIS_USE
    std::cout << "Deleting vismanager"<< std::endl;
    delete fVisManager;
    #endif

    std::cout << "Deleting runmanager"<< std::endl;
    if (fRunManager)
        delete fRunManager;

    std::cout << "Deleting raddata"<< std::endl;
    delete fRadData;
}
`

**Comment by waleey** [comment]
Hi, I again checked on this issue. On my end, the program still works fine even if I delete runManager. Example here:

![image](https://github.com/waleey/bulkice_doumeki/assets/25086848/f458b911-b68b-4843-997e-916fb1f8dc62)

The programs successfully prints "This is the end", which it wouldn't if deleting runManager (and any pointer in the runManager class's destructor) caused a segmentation fault. But I might be missing something or might be a hardware specific issue.
The segfault happens after return 0, which is basically the end of program. I am not sure how to fix this, but I will wait till next meeting and ask Prof. BenZvi
